#!/usr/bin/env node
/**
 * build-data.mjs
 * ---------------
 * 合并 projects/data.json (实时数据) + content/*.json (LLM 解读)
 * 输出 assets/data.js, 前端 <script> 直接加载
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DATA_PATH = resolve(ROOT, 'projects', 'data.json');
const CONTENT_DIR = resolve(ROOT, 'content');
const OUT = resolve(ROOT, 'assets', 'data.js');

const base = JSON.parse(readFileSync(DATA_PATH, 'utf8'));
const insights = {};
if (existsSync(CONTENT_DIR)) {
  for (const f of readdirSync(CONTENT_DIR).filter((x) => x.endsWith('.json'))) {
    const j = JSON.parse(readFileSync(resolve(CONTENT_DIR, f), 'utf8'));
    insights[j.id] = j;
  }
}

// 按 Star 数降序排
const projects = base.projects
  .map((p) => ({
    ...p,
    ...(insights[p.id] || {}),
  }))
  .sort((a, b) => (b.stars || 0) - (a.stars || 0));

const out = {
  ...base,
  projects,
  insights: Object.keys(insights).length,
  lastRefresh: base.lastRefresh || new Date().toISOString(),
};

const js = '/* AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand */\n' +
           'window.TOPHUB_DATA = ' + JSON.stringify(out) + ';\n';
writeFileSync(OUT, js, 'utf8');
console.log(`[build] wrote ${OUT} (${projects.length} projects, ${out.insights} insights)`);
